### PR TITLE
Added the basic CSS. Looks good!

### PR DESCRIPTION
**Pull request by u8y7541**
I did some of the CSS. It looks nice.

### CODE REVIEW

**Comment by aldencolerain** [comment]
Thanks! After I merge I'm going to make a few changes to make it work with the tournament page.

**Comment by u8y7541** [comment]
Oh, and by the way. I didn't edit the "layout" page yet. It looks awesome, but if I edit the layout page with all the ids and wrapper divs and stuff, it will look good. I could give u a screenshot of the css working with my edits.

**Comment by u8y7541** [comment]
Oh, I see the website. You've done some edits yourself.

**Comment by u8y7541** [comment]
Nice server list and reservation system! Must have taken a LOT of work!

**Comment by aldencolerain** [comment]
Thanks man.  It wasn't too bad.  I had it a while ago but didn't have a chance to put it up.  Thanks for the CSS!

**Comment by u8y7541** [comment]
BTW, you've added EXACTLY 1337 LINES OF CODE, the last time i checked.

**Pull request merged**
